// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pampazon.Api.Data;

#nullable disable

namespace Pampazon.Api.Data.Migrations
{
    [DbContext(typeof(PampazonDbContext))]
    [Migration("20250525230057_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pampazon.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CUIT")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Despacho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUITTransportista")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroDespacho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroDespacho")
                        .IsUnique();

                    b.ToTable("Despachos");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("DespachoId")
                        .HasColumnType("int");

                    b.Property<string>("DireccionDestinatario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreDestinatario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DespachoId");

                    b.HasIndex("NumeroOrden")
                        .IsUnique();

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Pampazon.Api.Models.OrdenItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<int?>("PosicionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("PosicionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenItems");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Posicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Estanteria")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Pasillo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Seccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Pasillo", "Seccion", "Estanteria", "Nivel")
                        .IsUnique()
                        .HasDatabaseName("IX_Posicion_UbicacionUnica");

                    b.ToTable("Posiciones");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AltoCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AnchoCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ProfundidadCm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProducto")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Remito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUITTransportista")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Remitos");
                });

            modelBuilder.Entity("Pampazon.Api.Models.RemitoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDeclarada")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadIngresada")
                        .HasColumnType("int");

                    b.Property<int?>("PosicionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("RemitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PosicionId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("RemitoId");

                    b.ToTable("RemitoItems");
                });

            modelBuilder.Entity("Pampazon.Api.Models.StockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PosicionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PosicionId");

                    b.HasIndex("ProductoId", "PosicionId")
                        .IsUnique()
                        .HasDatabaseName("IX_StockItem_ProductoPosicionUnica");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Orden", b =>
                {
                    b.HasOne("Pampazon.Api.Models.Cliente", "Cliente")
                        .WithMany("Ordenes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pampazon.Api.Models.Despacho", "Despacho")
                        .WithMany("OrdenesAsociadas")
                        .HasForeignKey("DespachoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Despacho");
                });

            modelBuilder.Entity("Pampazon.Api.Models.OrdenItem", b =>
                {
                    b.HasOne("Pampazon.Api.Models.Orden", "Orden")
                        .WithMany("Items")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pampazon.Api.Models.Posicion", "PosicionEgreso")
                        .WithMany("OrdenItemsEgreso")
                        .HasForeignKey("PosicionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pampazon.Api.Models.Producto", "Producto")
                        .WithMany("OrdenItems")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("PosicionEgreso");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Posicion", b =>
                {
                    b.HasOne("Pampazon.Api.Models.Cliente", "Cliente")
                        .WithMany("PosicionesAlquiladas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Remito", b =>
                {
                    b.HasOne("Pampazon.Api.Models.Cliente", "Cliente")
                        .WithMany("Remitos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Pampazon.Api.Models.RemitoItem", b =>
                {
                    b.HasOne("Pampazon.Api.Models.Posicion", "PosicionIngreso")
                        .WithMany("RemitoItemsIngreso")
                        .HasForeignKey("PosicionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pampazon.Api.Models.Producto", "Producto")
                        .WithMany("RemitoItems")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pampazon.Api.Models.Remito", "Remito")
                        .WithMany("Items")
                        .HasForeignKey("RemitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosicionIngreso");

                    b.Navigation("Producto");

                    b.Navigation("Remito");
                });

            modelBuilder.Entity("Pampazon.Api.Models.StockItem", b =>
                {
                    b.HasOne("Pampazon.Api.Models.Posicion", "Posicion")
                        .WithMany("StockItems")
                        .HasForeignKey("PosicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pampazon.Api.Models.Producto", "Producto")
                        .WithMany("StockItems")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posicion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Cliente", b =>
                {
                    b.Navigation("Ordenes");

                    b.Navigation("PosicionesAlquiladas");

                    b.Navigation("Remitos");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Despacho", b =>
                {
                    b.Navigation("OrdenesAsociadas");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Orden", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Posicion", b =>
                {
                    b.Navigation("OrdenItemsEgreso");

                    b.Navigation("RemitoItemsIngreso");

                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Producto", b =>
                {
                    b.Navigation("OrdenItems");

                    b.Navigation("RemitoItems");

                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("Pampazon.Api.Models.Remito", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
